server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: service-auth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: localhost
#    password:
management:
  endpoints:
    web:
      exposure:
        include: "*"
